AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "former2"
Description: ""
Resources:
    DynamoDBTable:
        Type: "AWS::DynamoDB::Table"
        DeletionPolicy: Delete
        Properties:
            AttributeDefinitions: 
              - 
                AttributeName: "id"
                AttributeType: "S"
            BillingMode: "PAY_PER_REQUEST"
            TableName: "ChatMessageTable"
            KeySchema: 
              - 
                AttributeName: "id"
                KeyType: "HASH"
            SSESpecification: 
                SSEEnabled: true
                SSEType: "KMS"
                KMSMasterKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/1f421a86-3eab-4e9d-a625-4f9d5796fadb"

    S3Bucket:
        Type: "AWS::S3::Bucket"
        DeletionPolicy: Delete
        Properties:
            BucketName: "sample-sample-sample"
            BucketEncryption: 
                ServerSideEncryptionConfiguration: 
                  - 
                    ServerSideEncryptionByDefault: 
                        SSEAlgorithm: "AES256"
                    BucketKeyEnabled: true

    S3Bucket2:
        Type: "AWS::S3::Bucket"
        DeletionPolicy: Delete
        Properties:
            BucketName: "parent-yoyoyo"
            BucketEncryption: 
                ServerSideEncryptionConfiguration: 
                  - 
                    ServerSideEncryptionByDefault: 
                        SSEAlgorithm: "AES256"
                    BucketKeyEnabled: false

    # AppSyncGraphQLApi:
    #     Type: "AWS::AppSync::GraphQLApi"
    #     Properties:
    #         Name: "ultrachat"
    #         AuthenticationType: "API_KEY"
    #         XrayEnabled: false

