// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChatMessage struct {
	ID        string `json:"id"`
	Message   string `json:"message"`
	CreatedAt string `json:"createdAt"`
}
