// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChatMessage struct {
	ID        string `json:"id"`
	Message   string `json:"message"`
	CreatedAt string `json:"createdAt"`
}

type Space struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
}

type UserInvitation struct {
	SenderID   int `json:"senderId"`
	ReceiverID int `json:"receiverId"`
	SpaceID    int `json:"spaceId"`
}
